global:
  imagePullPolicy: Always
  ###vault:
  ###  host: ip
  ###  name: vault
  ###  vaultToken: someToken


frontend:
### В чарте frontend отсутствуют некоторые важные файлы. Поймите какие и опишите их.
  replicas: 1
  revisionHistoryLimit: 15
  strategy:
    type: Recreate
  service:
    port: 80
  ingress:
    host: front-shavrov.2sem.students-projects.ru # Корректный домен будет указан в задании
    path: /
    pathType: Prefix
    tlsSecret: 2sem-students-projects-wildcard-secret
  containerPort: 80
  image: ${{ secrets.DOCKER_USER }}/sausage-frontend:latest
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "300m"
  nginxConf: nginx.conf

backend:
  annotations:
    path: /actuator/prometheus
    port: "8080"
    scrape: "true"
  config:
    postgresUri: jdbc:postgresql://postgresql:5432/sausage-store
    reportPath: /logs/reports
    logPath: /logs
  secrets:
    postgresUser: store
    postgresPassword: storepassword
    mongodbUri: mongodb://reports:reportspassword@mongodb:27017/sausage-store
  service:
    port: 8080
  revisionHistoryLimit: 15
  replicas: 1
  strategy:
  ### Опишите стратегию RollingUpdate для бэкенда
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  image: ${{ secrets.DOCKER_USER }}/sausage-backend:latest
  imagePullPolicy: Always
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "300m"
  containerPort: 8080
  livenessProbe:
  ### Опишите LivenessProbe для бэкенда
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 60
    periodSeconds: 30
    timeoutSeconds: 2
    failureThreshold: 6
  vpa:
  ### Опишите VPA для бэкенда
    updatePolicy:
      updateMode: "Off"
    resourcePolicy:
      containerPolicies:
        - containerName: "*"
          minAllowed:
            cpu: 25m
            memory: 128Mi
          maxAllowed:
            cpu: 300m
            memory: 512Mi
          controlledResources: ["cpu", "memory"]
          controlledValues: RequestsAndLimits

backend-report:
### Опишите значения для backend-report
  replicas: 1
  revisionHistoryLimit: 15
  image: ${{ secrets.DOCKER_USER }}/sausage-backend-report:latest
  containerPort: 8080
  service:
    port: 8080
  config:
    port: "8080"
    reportPath: /var/www-data/htdocs
  secrets:
    db: mongodb://reports:reportspassword@mongodb:27017/sausage-store
  resources:
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "500m"
  livenessProbe:
    httpGet:
      path: /api/v1/health
      port: 8080
    initialDelaySeconds: 15
    periodSeconds: 30
    timeoutSeconds: 2
    failureThreshold: 6
### Приложение должно использовать стратегию Recreate
  strategy:
    type: Recreate
### Приложение использует переменную PORT - порт, на котором оно запустится и DB - Uri-подключение к mongodb. 
### DB положите в Secret, PORT в ConfigMap
### Опишите HPA для backend-report
  hpa:
    minReplicas: 1
    maxReplicas: 5
    averageUtilization: 75

infra:
  postgresql:
  ### Опишите необходимые переменные для развертывания PostgresQL в кластере Kubernetes
    image: postgres:16
    containerPort: 5432
    env:
      POSTGRES_DB: sausage-store
      POSTGRES_USER: store
      POSTGRES_PASSWORD: storepassword
    storage: 256Mi
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "300m"
  mongodb:
    image: mongo:7.0
    containerPort: 27017
    env:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    resources:
      requests:
        memory: "128Mi"
        cpu: "50m"
      limits:
        memory: "256Mi"
        cpu: "250m"
    storage: 256Mi
    initJob:
      enabled: true
      database: sausage-store
      username: reports
      password: reportspassword
