---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-conf
  namespace: {{ .Release.Namespace }}
data:
  PORT: {{ .Values.env.port | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DB: "mongodb://{{ .Values.global.mongodb.reportUsername }}:{{ .Values.global.mongodb.reportPassword }}@{{ .Values.global.mongodb.host }}:{{ .Values.global.mongodb.port }}/{{ .Values.global.mongodb.database }}?authSource={{ .Values.global.mongodb.database }}&authMechanism=SCRAM-SHA-256"
