---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-conf
  namespace: {{ .Release.Namespace }}
data:
  postgres_uri: "jdbc:postgresql://{{ .Values.global.postgresql.host }}:{{ .Values.global.postgresql.port }}/{{ .Values.global.postgresql.database }}"
  report_path: {{ .Values.env.reportPath | quote }}
  log_path: {{ .Values.env.logPath | quote }}
{{- if .Values.global.vault.enabled }}
  vault_host: {{ .Values.global.vault.host | quote }}
  vault_scheme: {{ .Values.global.vault.scheme | quote }}
  vault_kv_enabled: {{ .Values.global.vault.kvEnabled | quote }}
{{- end }}
{{- if not .Values.global.vault.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  spring.datasource.username: {{ .Values.global.postgresql.username | quote }}
  spring.datasource.password: {{ .Values.global.postgresql.password | quote }}
  spring.data.mongodb.uri: "mongodb://{{ .Values.global.mongodb.reportUsername }}:{{ .Values.global.mongodb.reportPassword }}@{{ .Values.global.mongodb.host }}:{{ .Values.global.mongodb.port }}/{{ .Values.global.mongodb.database }}?authSource={{ .Values.global.mongodb.database }}&authMechanism=SCRAM-SHA-256"
{{- end }}
{{- if .Values.global.vault.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.vault.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  vault_token: {{ .Values.global.vault.vaultToken | quote }}
{{- end }}
