---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
type: Opaque
stringData:
  postgres_user: {{ .Values.secrets.postgresUser | quote }}
  postgres_password: {{ .Values.secrets.postgresPassword | quote }}
  mongodb_uri: {{ .Values.secrets.mongodbUri | quote }}
