spring.application.name=sausage-store
management.security.enabled=false

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

spring.cloud.vault.enabled=${SPRING_CLOUD_VAULT_ENABLED:false}
spring.cloud.vault.token=${SPRING_CLOUD_VAULT_TOKEN:}
spring.cloud.vault.scheme=${SPRING_CLOUD_VAULT_SCHEME:http}
spring.cloud.vault.host=${SPRING_CLOUD_VAULT_HOST:localhost}
spring.cloud.vault.kv.enabled=${SPRING_CLOUD_VAULT_KV_ENABLED:false}
spring.config.import=optional:vault://kv/${spring.application.name}

# Enable Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

#H2 settings
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
management.endpoint.prometheus.enabled=true
management.endpoints.web.exposure.include=health,prometheus
management.metrics.distribution.percentiles-histogram.http.server.requests=true
